# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="aphex"


# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git
vi-mode
zsh-autosuggestions
history-search-multi-word
pip
)

source $ZSH/oh-my-zsh.sh

# User configuration

HISTSIZE=999999999
SAVEHIST=$HISTSIZE
HISTFILE=~/.zsh_history

#aliases
alias rsend='rsync -avzP'
alias med='i=`ls /media/$USER/` && cd /media/$USER/$i'
export PATH=$PATH:/usr/local/bin:/media/ad/edfd3e93-afaa-4bce-b5bf-2111b26fcc0e/Xilinx_2018_1/Vivado/2018.1/bin/:/media/ad/edfd3e93-afaa-4bce-b5bf-2111b26fcc0e/Xilinx_2018_1/SDK/2018.1/bin/

# SYNT
#export PATH=$PATH:/media/ad/edfd3e93-afaa-4bce-b5bf-2111b26fcc0e/RISCV_TOOLS/sc-riscv64-unknown-elf-gcc-20180126-linux64/riscv-unknown-elf-gcc/bin/

#MY
#export PATH=$PATH:/media/ad/edfd3e93-afaa-4bce-b5bf-2111b26fcc0e/customtoolchain/riscv-tools/riscv/bin

#export RISCV=/media/ad/edfd3e93-afaa-4bce-b5bf-2111b26fcc0e/customtoolchain/riscv-tools/riscv/
export RISCV_COMPLIANCE_TESTS=/media/ad/edfd3e93-afaa-4bce-b5bf-2111b26fcc0e/riscv-compliance/
export GCC_COLORS=auto
stty -ixon
CK_PAGER=less
